### ISSUE TITLE
Docker run problem  : SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by kwiatks** [IBM/use-advanced-nlp-and-tone-analyser-to-analyse-speaker-insights#4]
convert-video-to-audio git:(master) ✗ docker --version
Docker version 20.10.7, build f0df350

docker image build -t convert-video-to-audio .
(build ran successfully)

➜  convert-video-to-audio git:(master) ✗ docker run -p 8080:8080 convert-video-to-audio
Traceback (most recent call last):
  File "app.py", line 1, in <module>
    from flask import Flask, render_template, request, redirect, jsonify
  File "/usr/local/lib/python3.5/dist-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
  File "/usr/local/lib/python3.5/dist-packages/jinja2/__init__.py", line 5, in <module>
    from .bccache import BytecodeCache as BytecodeCache
  File "/usr/local/lib/python3.5/dist-packages/jinja2/bccache.py", line 61
    self.code: t.Optional[CodeType] = None
             ^
SyntaxError: invalid syntax

**Comment by kwiatks** [comment]
Ignore - pasted to wrong github
